name: rabbitrinth
description: A maze game created with Dartlang.
version: 0.0.1
homepage: https://github.com/Salpico/WebTech
author:
- Claas R. <bengt.claas.rhodgess@stud.fh-luebeck.de>
- Marc-Niclas H. <marc-niclas.harm@stud.fh-luebeck.de>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
